# Add semantic Transmission strings to Spectran's language workbook.

transmission_language_rows <- tibble::tribble(
  ~key,
  ~Deutsch,
  ~English,
  "menu",
  "Transmission",
  "Transmission",
  "workflow_label",
  "Transmissionsbereiche",
  "Transmission sections",
  "tab_spectrum",
  "Transmissionsspektrum",
  "Transmission spectrum",
  "tab_measurement",
  "Details",
  "Details",
  "tab_normalization",
  "Normalisierung",
  "Normalization",
  "tab_results",
  "Ergebnisse",
  "Results",
  "tab_history",
  "Übernahme und Verlauf",
  "Promotion and History",
  "tab_export",
  "Export",
  "Export",
  "step_spectrum",
  "1. Spektrum",
  "1. Spectrum",
  "step_measurement",
  "2. Messung",
  "2. Measurement",
  "step_normalization",
  "3. Normalisierung",
  "3. Normalization",
  "step_apply",
  "4. Anwenden",
  "4. Apply",
  "step_promote",
  "5. Übernehmen",
  "5. Promote",
  "back",
  "Zurück",
  "Back",
  "continue",
  "Weiter",
  "Continue",
  "continue_measurement",
  "Weiter zur Messung",
  "Continue to measurement",
  "continue_details",
  "Weiter zu Details",
  "Continue to Details",
  "complete_details",
  "Erforderliche Details vervollständigen",
  "Complete required details",
  "continue_normalization",
  "Weiter zur Normalisierung",
  "Continue to normalization",
  "continue_apply",
  "Weiter zum Anwenden",
  "Continue to Apply",
  "continue_promotion",
  "Weiter zum Übernehmen",
  "Continue to promotion",
  "apply_and_results",
  "Filter anwenden und Ergebnisse anzeigen",
  "Apply filter and show Results",
  "continue_history",
  "Weiter zu Übernahme und Verlauf",
  "Continue to Promotion and History",
  "continue_export",
  "Weiter zum Export",
  "Continue to Export",
  "review_requirements",
  "Fehlende Angaben prüfen",
  "Review missing information",
  "choose_heading",
  "Transmissionsspektrum auswählen",
  "Choose a transmission spectrum",
  "choose_intro",
  "Laden Sie ein Transmissionsspektrum hoch oder wählen Sie eines aus. Die Vorschau zeigt, wie die verfügbaren Werte zur vervollständigten Kurve beitragen.",
  "Upload or select a transmission spectrum. The preview shows how the available values will contribute to the completed curve.",
  "source_label",
  "Quelle des Transmissionsspektrums",
  "Transmission-spectrum source",
  "source_catalogue",
  "Beispielkatalog",
  "Example catalogue",
  "source_upload",
  "CSV hochladen",
  "Upload CSV",
  "catalogue_collection",
  "Katalogsammlung",
  "Catalogue collection",
  "catalogue_featured",
  "Empfohlene Verglasungen, Blaulichtfilter und klinische Filter",
  "Featured glazing, blue-blocking, and clinical filters",
  "catalogue_all",
  "Alle 147 Filter",
  "All 147 filters",
  "catalogue_facade",
  "Fassaden- und Fensterverglasungen (26)",
  "Façade and window glazing (26)",
  "catalogue_spitschan",
  "Filter nach Spitschan et al. 2019 (121)",
  "Spitschan et al. 2019 filters (121)",
  "catalogue_category",
  "Filterkategorie",
  "Filter category",
  "catalogue_all_categories",
  "Alle Kategorien",
  "All categories",
  "catalogue_filter",
  "Filter suchen oder auswählen",
  "Search or select a filter",
  "catalogue_placeholder",
  "Hersteller oder Filtername eingeben",
  "Type a manufacturer or filter name",
  "csv_label",
  "Transmissions-CSV",
  "Transmission CSV",
  "csv_tooltip_label",
  "Informationen zu Transmissions-CSV-Dateien",
  "About transmission CSV files",
  "csv_tooltip",
  "Laden Sie eine Textdatei mit Wellenlängen- und Transmissionsspalte hoch. Verwenden Sie die flexiblen CSV-Einstellungen, wenn Trennzeichen, Dezimalzeichen, Kopfzeile oder Spaltenpositionen von den Voreinstellungen abweichen.",
  "Upload a delimited text file with wavelength and transmittance columns. Use Flexible CSV settings when its separator, decimal mark, header, or column positions differ from the defaults.",
  "template_download",
  "CSV-Vorlage mit konstant 100 % Transmission herunterladen",
  "Download 100% flat-transmittance CSV template",
  "csv_settings",
  "Flexible CSV-Einstellungen",
  "Flexible CSV settings",
  "measurement_heading",
  "Filtermessung beschreiben",
  "Describe the filter measurement",
  "measurement_intro",
  "Geben Sie an, wie die gemeldeten Werte zu interpretieren sind. Diese Entscheidungen werden für die Nachvollziehbarkeit zusammen mit dem angewendeten Ergebnis gespeichert.",
  "Confirm how the reported values should be interpreted. These decisions are stored with the applied result for audit.",
  "filter_name",
  "Filtername (erforderlich)",
  "Filter name (required)",
  "filter_name_tooltip_label",
  "Informationen zu Filternamen",
  "About filter names",
  "filter_name_tooltip",
  "Eine neue Datei oder ein Katalogeintrag erhält einen vorgeschlagenen Namen. Sie können ihn ändern. Ein leerer Name verhindert das Anwenden.",
  "A new file or catalogue entry receives a suggested name. You may replace it. An empty name blocks Apply.",
  "scale",
  "Transmissionsskala",
  "Transmission scale",
  "scale_tooltip_label",
  "Informationen zur Transmissionsskala",
  "About transmission scale",
  "scale_tooltip",
  "Bei Anteil werden Werte von 0 bis 1 erwartet. Bei Prozent werden Werte von 0 bis 100 erwartet. Die Normalisierungsvorschau zeigt immer Anteile.",
  "Fraction expects values from 0 to 1. Percent expects values from 0 to 100. The normalization preview always displays fractions.",
  "scale_choose",
  "Skala auswählen",
  "Choose a scale",
  "scale_fraction",
  "Anteil (0–1)",
  "Fraction (0–1)",
  "scale_percent",
  "Prozent (0–100)",
  "Percent (0–100)",
  "type",
  "Transmissionsart",
  "Transmittance type",
  "type_tooltip_label",
  "Informationen zu Transmissionsart und Filtermodell",
  "About transmittance type and filter model",
  "type_tooltip",
  "Die Gesamttransmission umfasst Verluste durch den gemessenen Filter oder das System. Die interne Transmission kann Oberflächenverluste ausschließen. Unbekannt bedeutet, dass die Messdefinition nicht angegeben wurde. Spectran modelliert passive, nicht fluoreszierende Filter. Ein fluoreszierendes Material kann Licht absorbieren und bei anderen Wellenlängen wieder emittieren. Diese wellenlängenweise Berechnung kann das nicht abbilden.",
  "Total includes losses through the measured filter or system. Internal may exclude surface losses. Unknown means the measurement definition was not supplied. Spectran models passive, non-fluorescent filters. A fluorescent material can absorb light and re-emit it at different wavelengths, which this wavelength-by-wavelength calculation cannot represent.",
  "type_choose",
  "Transmissionsart auswählen",
  "Choose a type",
  "type_total",
  "Gesamttransmission",
  "Total transmittance",
  "type_internal",
  "Interne Transmission",
  "Internal transmittance",
  "type_unknown",
  "Unbekannt",
  "Unknown",
  "type_ack",
  "Ich verstehe, dass diese Kurve möglicherweise nicht die Gesamttransmission des gesamten Systems beschreibt.",
  "I understand that this curve may not describe total whole-system transmission.",
  "scattering",
  "Streuende oder diffus transmittierende Probe",
  "Scattering or diffusing sample",
  "scattering_tooltip_label",
  "Informationen zu streuenden und diffus transmittierenden Proben",
  "About scattering and diffusing samples",
  "scattering_tooltip",
  "Wählen Sie Ja, wenn die Probe das transmittierte Licht auf verschiedene Richtungen verteilt. Die Ergebnisse hängen dann von der dokumentierten Messgeometrie ab.",
  "Choose Yes when the sample redistributes transmitted light across directions. Results then depend on the documented measurement geometry.",
  "yes",
  "Ja",
  "Yes",
  "no",
  "Nein",
  "No",
  "geometry",
  "Messgeometrie (bei streuenden Proben erforderlich)",
  "Measurement geometry (required for scattering samples)",
  "geometry_tooltip_label",
  "Informationen zur Messgeometrie",
  "About measurement geometry",
  "geometry_tooltip",
  "Beschreiben Sie Beleuchtungs- und Erfassungsgeometrie, zum Beispiel 8°/diffus mit Ulbrichtkugel. Bei streuenden oder diffus transmittierenden Proben ist diese Angabe erforderlich.",
  "Describe the illumination and collection geometry, for example 8 degrees/diffuse integrating sphere. This is required for scattering or diffusing samples.",
  "geometry_placeholder",
  "z. B. 8°/diffus mit Ulbrichtkugel",
  "e.g., 8°/diffuse integrating-sphere measurement",
  "angle",
  "Messwinkel (nur Metadaten)",
  "Measurement angle (metadata only)",
  "angle_tooltip_label",
  "Informationen zum Messwinkel",
  "About measurement angle",
  "angle_tooltip",
  "Der Winkel wird für Nachvollziehbarkeit und Export gespeichert. Er verändert weder die Transmissionskurve noch die Berechnungen in diesem Modul.",
  "The angle is retained for audit and export. It does not alter the transmission curve or calculations in this module.",
  "angle_placeholder",
  "z. B. senkrechter Einfall oder 8°",
  "e.g., normal incidence or 8°",
  "scattering_ack",
  "Ich verstehe, dass Ergebnisse für eine streuende Probe nur für die dokumentierte Messgeometrie gelten.",
  "I understand that results for a scattering sample apply only to the documented measurement geometry.",
  "normalization_heading",
  "Normalisierung vervollständigen",
  "Complete the normalization",
  "normalization_intro",
  "Prüfen Sie fehlende Randbereiche oder große interne Lücken. Jede Annahme erscheint sofort in der Live-Vorschau und wird für die Nachvollziehbarkeit gespeichert.",
  "Review any missing tails or large internal gaps. Every assumption appears immediately in the live preview and is stored for audit.",
  "preview_heading",
  "Vorschaugrafik",
  "Live normalization preview",
  "preview_no_curve",
  "Noch ist keine auswertbare Transmissionskurve verfügbar",
  "No parseable transmission curve yet",
  "preview_no_data",
  "Noch ist keine auswertbare Kurve verfügbar. Wählen Sie einen Katalogeintrag oder prüfen Sie Upload und CSV-Einstellungen. Die Vorschau bleibt während der Korrektur sichtbar.",
  "No parseable curve is available yet. Choose a catalogue record or check the upload and CSV settings. The preview remains here while you correct the input.",
  "preview_incomplete",
  "Die auswertbaren Messwerte werden bereits angezeigt. Bearbeiten Sie die erforderlichen Punkte, um die vervollständigte Kurve mit 401 Zeilen zu erzeugen.",
  "The parseable measurements are shown now. Resolve the readiness actions to produce the completed 401-row curve.",
  "preview_details",
  "Vorschaudaten und Konstruktionsdetails einblenden",
  "Show preview data and construction details",
  "download_preview_plot",
  "Transmissionsdiagramm herunterladen (PNG)",
  "Download transmittance plot (PNG)",
  "parsed_rows",
  "Eingelesene Transmissionszeilen",
  "Parsed transmission rows",
  "completed_status",
  "Status des vervollständigten Rasters",
  "Completed-grid status",
  "readiness_actions",
  "Erforderliche Schritte",
  "Actions required",
  "readiness_notes",
  "Hinweise (%d)",
  "Notes (%d)",
  "ready",
  "Bereit: Die vervollständigte Kurve enthält 401 Berechnungszeilen.",
  "Ready: the completed curve has 401 calculation rows.",
  "apply_heading",
  "Auf aktive Lichtquelle anwenden",
  "Apply to active light source",
  "apply_intro",
  "Anwenden speichert die aktuelle Quelle, den vervollständigten Filter, die Entscheidungen und Kennwerte in einem vorläufigen Ergebnis. Änderungen am Entwurf lassen das frühere Ergebnis sichtbar, kennzeichnen es aber als veraltet.",
  "Apply freezes the current source, completed filter, decisions, and metrics into one provisional snapshot. Editing the draft afterwards keeps the prior snapshot visible but marks it as out of date.",
  "apply_button",
  "Transmissionsfilter anwenden",
  "Apply transmission filter",
  "promote_heading",
  "Übernehmen und Verlauf",
  "Promote and history",
  "promote_intro",
  "Beim Übernehmen wird das aktuelle transmittierte Ergebnis zur aktiven Quelle. Das Wiederherstellen eines früheren Knotens verschiebt den aktiven Zeiger, ohne spätere Zweige zu löschen. Der Verlauf gilt nur für diese Shiny-Sitzung.",
  "Promotion makes the current transmitted result the active source. Restoring an earlier node moves the active pointer without deleting later branches. History lasts for this Shiny session only.",
  "promotion_name",
  "Name des zu übernehmenden Spektrums",
  "Name for promoted spectrum",
  "promotion_placeholder",
  "Quelle × Filter",
  "Source × filter",
  "promote_button",
  "Transmittiertes Spektrum übernehmen",
  "Promote transmitted spectrum",
  "restore_node",
  "Wiederherzustellender Verlaufsknoten",
  "History node to restore",
  "restore_button",
  "Ausgewählten Knoten wiederherstellen",
  "Restore selected node",
  "history_tree",
  "Sitzungsverlauf",
  "Session history tree",
  "archive_heading",
  "Archivierte übernommene Ergebnisse",
  "Archived promoted results",
  "archive_intro",
  "Durch das Übernehmen ändert sich die aktive Quelle, die zugrunde liegende Berechnung bleibt jedoch gültig. Wählen Sie einen übernommenen Knoten, um das gespeicherte Ergebnis anzusehen oder herunterzuladen. Ein erneutes Anwenden ist eine separate sequenzielle Filterberechnung.",
  "Promotion changes the active source, but it does not invalidate the calculation that produced it. Select any promoted node to inspect or download that frozen result. A new Apply is a separate sequential filtering calculation.",
  "archive_empty",
  "Ein übernommenes Ergebnis bleibt hier verfügbar, nachdem es zur aktiven Lichtquelle geworden ist.",
  "A promoted result will remain available here after it becomes the active light source.",
  "archive_select",
  "Zu betrachtendes übernommenes Ergebnis",
  "Promoted result to inspect",
  "download_provisional",
  "Aktuelles vorläufiges Ergebnis herunterladen",
  "Download current provisional result",
  "download_archive",
  "Ausgewähltes archiviertes Ergebnis herunterladen",
  "Download selected archived result",
  "download_completed",
  "Vervollständigter Filter (CSV)",
  "Completed filter CSV",
  "download_comparison",
  "Spektralvergleich (CSV)",
  "Spectral comparison CSV",
  "download_d65",
  "D65-Eigenschaften (CSV)",
  "D65 properties CSV",
  "download_metrics",
  "Angewendete Kennwerte (CSV)",
  "Applied metrics CSV",
  "download_history",
  "Verlauf (CSV)",
  "History CSV",
  "download_audit",
  "Audit-ZIP",
  "Audit ZIP",
  "download_plot",
  "Transmissionsdiagramm (PNG)",
  "Transmission plot (PNG)",
  "download_result_plot",
  "Ergebnisdiagramm (PNG)",
  "Result plot (PNG)",
  "download_filter_plot",
  "Transmissionsspektrum (PNG)",
  "Transmittance spectrum (PNG)",
  "plot_options",
  "Diagrammoptionen",
  "Plot options",
  "show_action_spectra",
  "Wirkfunktionen",
  "Action spectra",
  "show_transmittance_panel",
  "Transmissions-Teilbild B hinzufügen",
  "Add transmittance panel B",
  "show_incident_fill",
  "Einfallendes Spektrum heller einfärben",
  "Show incident spectrum with a lighter fill",
  "show_photopic_curve",
  "Photopische V(λ)-Funktion anzeigen",
  "Show photopic V(λ) function",
  "show_alphaopic_curves",
  "α-opische Wirkfunktionen anzeigen",
  "Show α-opic action spectra",
  "plot_result_subtitle",
  "Transmittiert (durchgezogen) und einfallend (gestrichelt)",
  "Transmitted (solid) and incident (dashed)",
  "plot_filter_panel",
  "Transmission",
  "Transmittance",
  "result_tab_d65",
  "D65-Eigenschaften",
  "D65 properties",
  "result_tab_light",
  "Lichtwerte",
  "Light values",
  "result_tab_balance",
  "Spektrale Balance",
  "Spectral balance",
  "d65_heading",
  "D65-bezogene Filtereigenschaften",
  "D65-referenced filter properties",
  "absolute_heading",
  "Absolute Werte vor und nach Transmission",
  "Incident and transmitted absolute values",
  "balance_heading",
  "Wirkfaktoren und Tageslicht-Effizienzverhältnisse",
  "Action factors and daylight efficacy ratios",
  "gt_d65_subtitle",
  "Gewichtet mit CIE D65",
  "Weighted against CIE D65",
  "gt_transmittance_spanner",
  "Transmission",
  "Transmittance",
  "gt_light_values_spanner",
  "Lichtwerte",
  "Light values",
  "gt_balance_values_spanner",
  "Werte",
  "Values",
  "gt_change_spanner",
  "Änderung",
  "Change",
  "gt_d65_note",
  "D65-bezogene gewichtete Transmission im Berechnungsraster von 380–780 nm.",
  "D65-referenced weighted transmittance on the 380–780 nm calculation grid.",
  "gt_retained_note",
  "Für beibehaltene Anteile dient die aktive einfallende Quelle als Nenner.",
  "Retained values use the active incident source as denominator.",
  "undefined_heading",
  "Warum einige Werte nicht definiert sind",
  "Why some values are Undefined",
  "technical_details",
  "Technische Nennerdetails (%d Erläuterungen)",
  "Technical denominator details (%d explanations)",
  "technical_detail",
  "Technisches Nennerdetail (1 Erläuterung)",
  "Technical denominator detail (1 explanation)",
  "ready_to_apply",
  "Der aktuelle Filter kann angewendet werden.",
  "Ready to apply the current filter.",
  "no_provisional",
  "Noch kein vorläufiges Ergebnis. Bearbeiten Sie die erforderlichen Punkte oben und stellen Sie eine aktive Quelle bereit.",
  "No provisional result yet. Complete the readiness actions above and provide an active source.",
  "stale_valid",
  "Die Ergebnisse sind veraltet. Wenden Sie den aktuellen Filter erneut an.",
  "Results are out of date. Apply the current filter again.",
  "results_archived",
  "Unten wird ein gültiges, übernommenes Ergebnis angezeigt. Wenden Sie den Filter erneut an, um eine separate sequenzielle Berechnung mit %s als aktiver Quelle zu erstellen.",
  "A valid promoted result is shown below. Apply again to create a separate sequential calculation using %s as the active source.",
  "frozen_result_heading",
  "Eingefrorenes Übernahmeergebnis",
  "Frozen promoted result",
  "frozen_result_intro",
  "Diese gültige Berechnung hat das übernommene Spektrum erzeugt und bleibt zur Prüfung und zum Export unverändert verfügbar.",
  "This valid calculation produced the promoted spectrum and remains unchanged for inspection and export.",
  "stale_invalid",
  "Die Ergebnisse sind veraltet. Bearbeiten Sie die aktuellen erforderlichen Punkte, bevor Sie den Filter erneut anwenden.",
  "Results are out of date. Resolve the current readiness actions before applying again.",
  "results_current",
  "Die Ergebnisse für %s sind aktuell.",
  "Results are current for %s.",
  "source_unavailable",
  "Aktive Quelle nicht verfügbar.",
  "Active source unavailable.",
  "results_after_apply",
  "Spektralvergleich und Kennwerttabellen erscheinen nach dem Anwenden.",
  "The spectral comparison and metric tables will appear after Apply.",
  "balance_intro",
  "Diese dimensionslosen Kennwerte zur spektralen Balance zeigen absolute und relative Änderungen. Sie werden nicht als beibehaltene Prozentanteile bezeichnet.",
  "These dimensionless spectral-balance metrics show absolute and relative changes. They are not labelled as retained percentages.",
  "table_property",
  "Eigenschaft",
  "Property",
  "table_symbol",
  "Symbol",
  "Symbol",
  "table_fraction",
  "Anteil",
  "Fraction",
  "table_percent",
  "Prozent",
  "Percent",
  "table_metric",
  "Kennwert",
  "Metric",
  "table_incident",
  "Einfallend",
  "Incident",
  "table_transmitted",
  "Transmittiert",
  "Transmitted",
  "table_unit",
  "Einheit",
  "Unit",
  "table_retained",
  "Beibehalten",
  "Retained",
  "table_absolute_change",
  "Absolute Änderung",
  "Absolute change",
  "table_relative_change",
  "Relative Änderung",
  "Relative change",
  "history_initial",
  "Der Verlauf beginnt, sobald eine aktive Quelle importiert wurde.",
  "History will start when an active source is imported.",
  "history_no_source",
  "Für den Sitzungsverlauf ist keine aktive Quelle verfügbar.",
  "No active source is available for session history.",
  "history_new_root",
  "Neue Quelle importiert. Der Verlauf enthält jetzt den sichtbaren Wurzelknoten %s.",
  "New source imported. History now contains the visible root node %s.",
  "promotion_unavailable",
  "Übernehmen ist nicht verfügbar. Wenden Sie den aktuellen gültigen Filter an, bevor Sie ihn übernehmen.",
  "Promotion is unavailable. Apply the current valid filter before promoting it.",
  "promotion_name_required",
  "Geben Sie einen Namen ein, bevor Sie das transmittierte Spektrum übernehmen.",
  "Enter a name before promoting the transmitted spectrum.",
  "promoted_status",
  "%s wurde als %s übernommen. Das angewendete Ergebnis bleibt unter Archivierte übernommene Ergebnisse verfügbar. Wenden Sie den Filter nur erneut an, um eine neue sequenzielle Filterung zu berechnen.",
  "Promoted %s as %s. The applied result remains available in Archived promoted results. Apply again only to calculate a new sequential filter.",
  "restored_status",
  "%s wurde wiederhergestellt: %s. Bestehende Zweige wurden beibehalten.",
  "Restored %s: %s. Existing branches were preserved.",
  "history_sequence",
  "Reihenfolge",
  "Sequence",
  "history_node",
  "Knoten",
  "Node",
  "history_parent",
  "Übergeordnet",
  "Parent",
  "history_root",
  "Wurzel",
  "Root",
  "history_name",
  "Spektrumname",
  "Spectrum name",
  "history_created_by",
  "Erzeugt durch",
  "Created by",
  "history_active",
  "Aktiv",
  "Active",
  "history_active_suffix",
  "(aktiv)",
  "(active)",
  "history_import",
  "Quellenimport",
  "Source import",
  "history_promotion",
  "Transmissionsübernahme",
  "Transmission promotion",
  "import_confirm_heading",
  "Sitzungsverlauf löschen?",
  "Clear session history?",
  "import_cancel",
  "Abbrechen",
  "Cancel",
  "import_confirm_action",
  "Importieren und Verlauf löschen",
  "Import and clear history",
  "import_direct",
  "%s wurde als neue Wurzel des Sitzungsverlaufs importiert.",
  "Imported %s as the new session-history root.",
  "import_confirmation_required",
  "Vor dem Import von %s ist eine Bestätigung erforderlich.",
  "Confirmation required before importing %s.",
  "import_cancelled",
  "Import abgebrochen. %s wurde nicht importiert. Die aktuelle Quelle und der Verlauf wurden beibehalten.",
  "Import cancelled. %s was not imported, and the current source and history were kept.",
  "import_completed_one",
  "%s wurde als neue Wurzel des Verlaufs importiert. 1 übernommener Knoten und alle vorherigen Zweige wurden entfernt.",
  "Imported %s as the new history root. Removed 1 promoted node and all prior branches.",
  "import_completed_many",
  "%s wurde als neue Wurzel des Verlaufs importiert. %d übernommene Knoten und alle vorherigen Zweige wurden entfernt.",
  "Imported %s as the new history root. Removed %d promoted nodes and all prior branches.",
  "import_confirm_message_one",
  "Beim Import von %s werden 1 übernommener Verlaufsknoten und alle Zweige dieser Sitzung entfernt.",
  "Importing %s will remove 1 promoted history node and every branch from this session.",
  "import_confirm_message_many",
  "Beim Import von %s werden alle %d übernommenen Verlaufsknoten und alle Zweige dieser Sitzung entfernt.",
  "Importing %s will remove all %d promoted history nodes and every branch from this session.",
  "import_confirm_irreversible",
  "Dies kann nicht rückgängig gemacht werden. Die ausgewählte Quelle wird zur einzigen sichtbaren Wurzel des Verlaufs.",
  "This cannot be undone. The selected source will become the only visible history root.",
  "download_help",
  "Diese Bedienelemente beziehen sich auf das aktuelle vorläufige Ergebnis. Eine Änderung deaktiviert sie, bis erneut Anwenden gedrückt wurde. Übernommene Ergebnisse behalten ihre eigenen Downloads im Archiv oben.",
  "These controls apply to the current provisional result. A change disables them until Apply is pressed again. Promoted results retain their own downloads in the archive above.",
  "catalogue_choose",
  "Wählen Sie einen Katalogfilter, um Quelle und Abdeckung zu prüfen.",
  "Choose a catalogue filter to inspect its source and coverage.",
  "catalogue_coverage",
  "%s. Abdeckung der Quellkurve: %s.",
  "%s. Source curve coverage: %s.",
  "source",
  "Quelle",
  "Source",
  "citation",
  "Zitation",
  "Citation",
  "licence",
  "Lizenz",
  "Licence",
  "status_supplied",
  "Gelieferter Messwert",
  "Supplied measurement",
  "status_interpolated",
  "Interpoliert (Lücke ≤5 nm)",
  "Interpolated (gap ≤5 nm)",
  "status_large_ack",
  "Interpolation über große Lücke (bestätigt)",
  "Large-gap interpolation (acknowledged)",
  "status_large_wait",
  "Große Lücke wartet auf Bestätigung",
  "Large gap awaiting acknowledgement",
  "status_lower_assumed",
  "Unterer Randbereich konstant angenommen",
  "Lower tail assumed constant",
  "status_upper_assumed",
  "Oberer Randbereich konstant angenommen",
  "Upper tail assumed constant",
  "status_lower_carried",
  "Erster Messwert bis 380 nm rückwärts fortgeführt",
  "First supplied value carried backward to 380 nm",
  "status_upper_carried",
  "Letzter Messwert bis 780 nm vorwärts fortgeführt",
  "Last supplied value carried forward to 780 nm",
  "status_lower_wait",
  "Unterer Randbereich wartet auf Auswahl",
  "Lower tail awaiting a choice",
  "status_upper_wait",
  "Oberer Randbereich wartet auf Auswahl",
  "Upper tail awaiting a choice",
  "status_outside",
  "Außerhalb 380–780 nm (nur Audit)",
  "Outside 380–780 nm (audit only)",
  "preview_source_row",
  "Quellzeile",
  "Source row",
  "preview_wavelength",
  "Wellenlänge (nm)",
  "Wavelength (nm)",
  "preview_input",
  "Eingabewert",
  "Input value",
  "preview_scaled",
  "Skalierte Transmission (Anteil)",
  "Scaled transmittance (fraction)",
  "preview_inside",
  "Im Berechnungsbereich?",
  "Inside calculation range?",
  "preview_status",
  "Status",
  "Status",
  "preview_samples",
  "Werte",
  "Samples",
  "metric_tau_v_d65",
  "Lichttransmissionsgrad",
  "Luminous transmittance",
  "metric_tau_mel_d65",
  "Melanopischer Transmissionsgrad",
  "Melanopic transmittance",
  "metric_tau_l_cone_d65",
  "L-Zapfen-Transmissionsgrad",
  "L-cone-opic transmittance",
  "metric_tau_m_cone_d65",
  "M-Zapfen-Transmissionsgrad",
  "M-cone-opic transmittance",
  "metric_tau_s_cone_d65",
  "S-Zapfen-Transmissionsgrad",
  "S-cone-opic transmittance",
  "metric_tau_rh_d65",
  "Rhodopischer Transmissionsgrad",
  "Rhodopic transmittance",
  "metric_total_irradiance",
  "Gesamtbestrahlungsstärke",
  "Total irradiance",
  "metric_photopic_illuminance",
  "Photopische Beleuchtungsstärke",
  "Photopic illuminance",
  "metric_melanopic_irradiance",
  "Melanopische Bestrahlungsstärke",
  "Melanopic irradiance",
  "metric_melanopic_edi",
  "Melanopische EDI",
  "Melanopic EDI",
  "metric_melanopic_action_factor",
  "Melanopischer Wirkfaktor",
  "Melanopic action factor",
  "metric_melanopic_der",
  "Melanopische DER",
  "Melanopic DER",
  "metric_l_cone_opic_irradiance",
  "L-Zapfen-Bestrahlungsstärke",
  "L-cone-opic irradiance",
  "metric_l_cone_opic_edi",
  "L-Zapfen-EDI",
  "L-cone-opic EDI",
  "metric_l_cone_opic_action_factor",
  "L-Zapfen-Wirkfaktor",
  "L-cone-opic action factor",
  "metric_l_cone_opic_der",
  "L-Zapfen-DER",
  "L-cone-opic DER",
  "metric_m_cone_opic_irradiance",
  "M-Zapfen-Bestrahlungsstärke",
  "M-cone-opic irradiance",
  "metric_m_cone_opic_edi",
  "M-Zapfen-EDI",
  "M-cone-opic EDI",
  "metric_m_cone_opic_action_factor",
  "M-Zapfen-Wirkfaktor",
  "M-cone-opic action factor",
  "metric_m_cone_opic_der",
  "M-Zapfen-DER",
  "M-cone-opic DER",
  "metric_s_cone_opic_irradiance",
  "S-Zapfen-Bestrahlungsstärke",
  "S-cone-opic irradiance",
  "metric_s_cone_opic_edi",
  "S-Zapfen-EDI",
  "S-cone-opic EDI",
  "metric_s_cone_opic_action_factor",
  "S-Zapfen-Wirkfaktor",
  "S-cone-opic action factor",
  "metric_s_cone_opic_der",
  "S-Zapfen-DER",
  "S-cone-opic DER",
  "metric_rhodopic_irradiance",
  "Rhodopische Bestrahlungsstärke",
  "Rhodopic irradiance",
  "metric_rhodopic_edi",
  "Rhodopische EDI",
  "Rhodopic EDI",
  "metric_rhodopic_action_factor",
  "Rhodopischer Wirkfaktor",
  "Rhodopic action factor",
  "metric_rhodopic_der",
  "Rhodopische DER",
  "Rhodopic DER",
  "warning_zero_source",
  "Diese Quelle hat eine Bestrahlungsstärke und Beleuchtungsstärke von null. Beibehaltene Prozentanteile, Wirkfaktoren und DER können nicht berechnet werden. Betroffene Zellen werden als Nicht definiert angezeigt.",
  "This source has zero irradiance and illuminance. Retained percentages, action factors, and DERs cannot be calculated; affected cells are shown as Undefined.",
  "warning_precision_source",
  "Bestrahlungsstärke und Beleuchtungsstärke dieser Quelle liegen auf oder unter Maschinengenauigkeit. Beibehaltene Prozentanteile können nicht berechnet werden.",
  "This source's irradiance and illuminance are at or below machine precision. Retained percentages cannot be calculated.",
  "warning_retained",
  "Einige beibehaltene Prozentanteile können nicht berechnet werden, weil die einfallend gewichteten Wirkungen null, nicht endlich oder auf Maschinengenauigkeit liegen.",
  "Some retained percentages cannot be calculated because their incident weighted responses are zero, non-finite, or at machine precision.",
  "warning_zero_transmitted",
  "Das transmittierte Licht hat eine photopische Beleuchtungsstärke von null. Wirkfaktoren und DER können nicht berechnet werden.",
  "The transmitted light has zero photopic illuminance. Action factors and DERs cannot be calculated.",
  "warning_precision_transmitted",
  "Die transmittierte photopische Beleuchtungsstärke liegt auf oder unter Maschinengenauigkeit. Wirkfaktoren und DER können nicht berechnet werden.",
  "The transmitted photopic illuminance is at or below machine precision. Action factors and DERs cannot be calculated.",
  "warning_balance",
  "Einige Wirkfaktoren und DER können nicht berechnet werden, weil ein erforderlicher Nenner null, nicht endlich oder auf Maschinengenauigkeit ist.",
  "Some action factors and DERs cannot be calculated because a required denominator is zero, non-finite, or at machine precision.",
  "warning_undefined_cells",
  "Betroffene Zellen werden als Nicht definiert angezeigt.",
  "Affected cells are shown as Undefined.",
  "warning_group_d65",
  "D65-bezogene Eigenschaften",
  "D65-referenced properties",
  "warning_group_retained",
  "Beibehaltene Anteile",
  "Retained proportions",
  "warning_group_action",
  "Wirkfaktoren",
  "Action factors",
  "warning_group_der",
  "Tageslicht-Effizienzverhältnisse",
  "Daylight efficacy ratios",
  "warning_group_other",
  "Weitere Kennwerte",
  "Other metrics",
  "explanation_one",
  "%s (1 Erläuterung)",
  "%s (1 explanation)",
  "explanation_many",
  "%s (%d Erläuterungen)",
  "%s (%d explanations)",
  "csv_heading",
  "CSV-Einstellungen",
  "CSV settings",
  "csv_skip",
  "Zu überspringende Zeilen",
  "Rows to skip",
  "csv_wavelength",
  "Wellenlängenspalte",
  "Wavelength column",
  "csv_value",
  "Transmissionsspalte",
  "Transmission column",
  "csv_separator",
  "Spaltentrennzeichen",
  "Column separator",
  "csv_whitespace",
  "Leerraum",
  "Whitespace",
  "csv_decimal",
  "Dezimalzeichen",
  "Decimal mark",
  "csv_point",
  "Punkt (Beispiel: 0.5)",
  "Point (example: 0.5)",
  "csv_comma",
  "Komma (Beispiel: 0,5)",
  "Comma (example: 0,5)",
  "csv_header",
  "Erste Zeile enthält Spaltennamen",
  "First row contains column names",
  "csv_reset",
  "Einstellungen zurücksetzen",
  "Reset settings",
  "csv_invalid_columns",
  "Wählen Sie zwei verschiedene Spalten aus, die in der Datei vorhanden sind.",
  "Select two different columns that exist in the file.",
  "file_browse",
  "Durchsuchen",
  "Browse",
  "file_none",
  "Keine Datei ausgewählt",
  "No file selected",
  "not_ready_one",
  "Nicht bereit: 1 Schritt erforderlich",
  "Not ready: 1 action required",
  "not_ready_many",
  "Nicht bereit: %d Schritte erforderlich",
  "Not ready: %d actions required",
  "note_one",
  "1 Hinweis",
  "1 note",
  "note_many",
  "%d Hinweise",
  "%d notes",
  "require_source",
  "Wählen Sie einen Katalogfilter, laden Sie eine Transmissions-CSV hoch oder wählen Sie eine Demokurve.",
  "Select a catalogue filter, upload a transmission CSV, or choose a showcase fixture.",
  "require_name",
  "Geben Sie einen Filternamen ein.",
  "Enter a filter name.",
  "require_type",
  "Wählen Sie eine Transmissionsart.",
  "Choose a transmittance type.",
  "require_type_ack",
  "Bestätigen Sie, dass interne oder unbekannte Transmission nicht die Gesamttransmission des gesamten Systems darstellt.",
  "Acknowledge that internal or unknown transmittance does not represent whole-system total transmission.",
  "require_geometry",
  "Dokumentieren Sie die Messgeometrie für eine streuende Probe.",
  "Document the measurement geometry for a scattering sample.",
  "require_scattering_ack",
  "Bestätigen Sie, dass Ergebnisse für streuende Proben von der Messgeometrie abhängen.",
  "Acknowledge that scattering results are geometry-specific.",
  "tail_lower_label",
  "Fehlender unterer Randbereich: %s",
  "Missing lower tail: %s",
  "tail_upper_label",
  "Fehlender oberer Randbereich: %s",
  "Missing upper tail: %s",
  "tail_choose",
  "Vervollständigung dieses Bereichs auswählen",
  "Choose how to complete this interval",
  "tail_opaque",
  "Opak: 0 % Transmission annehmen",
  "Opaque: assume 0% transmittance",
  "tail_transparent",
  "Transparent: 100 % Transmission annehmen",
  "Transparent: assume 100% transmittance",
  "tail_carry_first",
  "Ersten Messwert rückwärts bis 380 nm fortführen",
  "Carry the first supplied value backward to 380 nm",
  "tail_carry_last",
  "Letzten Messwert vorwärts bis 780 nm fortführen",
  "Carry the last supplied value forward to 780 nm",
  "tail_lower_help",
  "Der gewählte Wert bleibt über %s konstant und kann bei der ersten gelieferten Wellenlänge (%s nm) eine Stufe erzeugen.",
  "The selected value remains constant across %s and may step at the first supplied wavelength (%s nm).",
  "tail_upper_help",
  "Der gewählte Wert bleibt über %s konstant und kann nach der letzten gelieferten Wellenlänge (%s nm) eine Stufe erzeugen.",
  "The selected value remains constant across %s and may step after the last supplied wavelength (%s nm).",
  "large_gap_label",
  "Große Lücken mit Bestätigungspflicht: %s",
  "Large gaps requiring acknowledgement: %s",
  "large_gap_ack",
  "Stückweise lineare Interpolation über diese Lücken zulassen.",
  "Allow piecewise-linear interpolation across these gaps.",
  "coverage_complete",
  "Keine Randergänzung erforderlich",
  "No boundary completion is needed",
  "coverage_complete_help",
  "Die gelieferte Kurve enthält Werte bei 380 nm und 780 nm. Sie können ohne Annahme für einen unteren oder oberen Randbereich fortfahren.",
  "The supplied curve includes values at 380 nm and 780 nm. You can continue without making a lower-tail or upper-tail assumption.",
  "missing_modal_title",
  "Vor dem Anwenden fehlen noch Angaben",
  "Information is still needed before Apply",
  "missing_modal_intro",
  "Bearbeiten Sie die folgenden Punkte. Mit den Schaltflächen gelangen Sie direkt zum passenden Bereich; Ihr aktueller Entwurf bleibt erhalten.",
  "Resolve the following items. The buttons open the relevant section directly, and your current draft is preserved.",
  "missing_group_spectrum",
  "Transmissionsspektrum",
  "Transmission spectrum",
  "missing_group_details",
  "Details",
  "Details",
  "missing_group_normalization",
  "Normalisierung",
  "Normalization",
  "go_to_spectrum",
  "Transmissionsspektrum öffnen",
  "Open Transmission spectrum",
  "go_to_details",
  "Details öffnen",
  "Open Details",
  "go_to_normalization",
  "Normalisierung öffnen",
  "Open Normalization",
  "modal_close",
  "Schließen",
  "Close",
  "export_heading",
  "Transmissionsergebnisse exportieren",
  "Export transmission results",
  "export_intro",
  "Wählen Sie ein aktuelles oder archiviertes Ergebnis und laden Sie Diagramme, Tabellen und prüfbare Daten einzeln oder als Paket herunter.",
  "Choose a current or archived result, then download figures, tables, and auditable data individually or as a bundle.",
  "export_result",
  "Zu exportierendes Ergebnis",
  "Result to export",
  "export_current",
  "Aktuelles vorläufiges Ergebnis",
  "Current provisional result",
  "export_none",
  "Kein exportierbares Ergebnis verfügbar",
  "No exportable result is available",
  "export_figures",
  "Abbildungen",
  "Figures",
  "export_tables",
  "Tabellen",
  "Tables",
  "export_data",
  "Daten und Audit",
  "Data and audit",
  "export_plot_settings",
  "Diagrammeinstellungen",
  "Graph settings",
  "export_plot_settings_intro",
  "Die aktuellen Diagrammoptionen aus Ergebnisse werden für den Export verwendet.",
  "The current plot choices from Results are used for export.",
  "export_plot_width",
  "Breite (Zoll)",
  "Width (inches)",
  "export_plot_height",
  "Höhe (Zoll)",
  "Height (inches)",
  "export_font_size",
  "Schriftgröße",
  "Font size",
  "export_scale_max",
  "Maximum der Bestrahlungsstärke (mW/m²/nm, optional)",
  "Maximum irradiance (mW/m²/nm, optional)",
  "export_scale_invalid",
  "Geben Sie eine positive Zahl ein oder lassen Sie das Feld leer.",
  "Enter a positive number or leave the field blank.",
  "export_plot_table_metric",
  "Tabelle für Diagramm und Tabelle",
  "Table for plot plus table",
  "download_plot_table",
  "Diagramm und Tabelle (PNG)",
  "Plot plus table (PNG)",
  "export_bundle_heading",
  "Exportpaket zusammenstellen",
  "Build export bundle",
  "export_bundle_intro",
  "Wählen Sie die Dateien für ein gemeinsames ZIP-Paket aus.",
  "Select the files to include in one ZIP bundle.",
  "export_bundle_summary",
  "%d Dateien ausgewählt",
  "%d files selected",
  "export_bundle_progress_heading",
  "ZIP-Paket wird erstellt",
  "Creating ZIP bundle",
  "export_bundle_progress_detail",
  "%d ausgewählte Dateien werden vorbereitet. Der Download steht danach bereit.",
  "%d selected files are being prepared. The download will be ready when preparation is complete.",
  "export_bundle_ready",
  "Das ZIP-Paket ist bereit. Laden Sie es mit der Schaltfläche unten herunter.",
  "The ZIP bundle is ready. Download it with the button below.",
  "download_bundle_ready",
  "Vorbereitetes ZIP-Paket herunterladen",
  "Download prepared ZIP bundle",
  "export_quick_heading",
  "Einzelne Dateien schnell herunterladen",
  "Quickly download individual files",
  "export_bundle_result_plot",
  "Ergebnisdiagramm (PNG)",
  "Result plot (PNG)",
  "export_bundle_filter_plot",
  "Transmissionsspektrum (PNG)",
  "Transmittance spectrum (PNG)",
  "export_bundle_plot_table",
  "Diagramm und Tabelle (PNG)",
  "Plot plus table (PNG)",
  "export_bundle_d65_png",
  "D65-Tabelle (PNG)",
  "D65 table (PNG)",
  "export_bundle_light_png",
  "Lichtwerte-Tabelle (PNG)",
  "Light values table (PNG)",
  "export_bundle_balance_png",
  "Spektrale-Balance-Tabelle (PNG)",
  "Spectral balance table (PNG)",
  "export_bundle_completed_csv",
  "Vervollständigter Filter (CSV)",
  "Completed filter (CSV)",
  "export_bundle_comparison_csv",
  "Spektralvergleich (CSV)",
  "Spectral comparison (CSV)",
  "export_bundle_d65_csv",
  "D65-Eigenschaften (CSV)",
  "D65 properties (CSV)",
  "export_bundle_light_csv",
  "Lichtwerte (CSV)",
  "Light values (CSV)",
  "export_bundle_balance_csv",
  "Spektrale Balance (CSV)",
  "Spectral balance (CSV)",
  "export_bundle_history_csv",
  "Verlauf (CSV)",
  "History (CSV)",
  "export_bundle_audit_zip",
  "Audit-ZIP",
  "Audit ZIP",
  "download_d65_table_png",
  "D65-Tabelle (PNG)",
  "D65 table (PNG)",
  "download_light_table_png",
  "Lichtwerte-Tabelle (PNG)",
  "Light values table (PNG)",
  "download_balance_table_png",
  "Spektrale-Balance-Tabelle (PNG)",
  "Spectral balance table (PNG)",
  "download_light_table_csv",
  "Lichtwerte-Tabelle (CSV)",
  "Light values table (CSV)",
  "download_balance_table_csv",
  "Spektrale-Balance-Tabelle (CSV)",
  "Spectral balance table (CSV)",
  "download_bundle",
  "Ausgewähltes ZIP-Paket erstellen",
  "Create selected ZIP bundle",
  "watermark_created_with",
  "erstellt mit ",
  "created with ",
  "parsed_caption",
  "Die ersten %d von %d eingelesenen Zeilen werden angezeigt.",
  "Showing first %d of %d parsed rows.",
  "parsed_counts",
  "%d innerhalb von 380–780 nm; %d außerhalb. %s.",
  "%d inside 380–780 nm; %d outside. %s.",
  "scale_fraction_shown",
  "Eingabe als Anteil; skalierter Anteil wird gezeigt",
  "Fraction input; scaled fraction shown",
  "scale_percent_shown",
  "Eingabe in Prozent; skalierter Anteil wird gezeigt",
  "Percent input; scaled fraction shown",
  "completed_caption",
  "%d vervollständigte Zeilen im Berechnungsraster von 380–780 nm mit 1 nm Schrittweite.",
  "%d completed rows on the 380–780 nm, 1 nm calculation grid.",
  "diagnostic_sorted",
  "Die Eingabewellenlängen waren nicht sortiert und wurden sortiert.",
  "Input wavelengths were out of order and have been sorted.",
  "diagnostic_outside",
  "%d gelieferte Werte liegen außerhalb von 380–780 nm. Sie bleiben für Audit und Randinterpolation erhalten, werden aber nicht in die Berechnungen einbezogen.",
  "%d supplied sample(s) lie outside 380–780 nm. They are retained for audit and boundary bracketing but excluded from calculations.",
  "diagnostic_external_intervals",
  "Die Intervalle außerhalb des Berechnungsbereichs (%s) enthalten keine Werte des vervollständigten 380–780-nm-Rasters. Sie werden für Audit und Randkontext gezeigt, benötigen aber keine Interpolationsbestätigung.",
  "Outside-domain interval(s) %s contain no completed 380–780 nm grid samples. They are shown for audit and boundary context but require no interpolation consent.",
  "require_lower_tail",
  "Wählen Sie, wie der untere Randbereich (%s) vervollständigt wird: opak mit 0 %%, transparent mit 100 %% oder durch Rückwärtsfortführung des ersten Messwerts.",
  "Choose how to complete the lower tail (%s): opaque at 0%%, transparent at 100%%, or by carrying the first supplied value backward.",
  "require_upper_tail",
  "Wählen Sie, wie der obere Randbereich (%s) vervollständigt wird: opak mit 0 %%, transparent mit 100 %% oder durch Vorwärtsfortführung des letzten Messwerts.",
  "Choose how to complete the upper tail (%s): opaque at 0%%, transparent at 100%%, or by carrying the last supplied value forward.",
  "require_gap",
  "Bestätigen Sie die lineare Interpolation über %d interne Lücke(n), die größer als %s nm sind.",
  "Acknowledge linear interpolation across %d internal gap(s) larger than %s nm.",
  "import_unlocks_transmission",
  "Importieren Sie zuerst ein Quellspektrum. Danach öffnet sich die Auswertung. Transmission wird als optionale Seite nach Export freigeschaltet.",
  "Import a source spectrum first. Analysis opens afterwards, and Transmission is unlocked as an optional page after Export.",
  "catalogue_version",
  "Quellversion",
  "Source version",
  "catalogue_revision",
  "Fixierter Git-Stand",
  "Pinned Git revision",
  "catalogue_measurement_details",
  "Mess- und Verarbeitungsdetails",
  "Measurement and processing details",
  "catalogue_description",
  "Quellbeschreibung",
  "Source description",
  "catalogue_geometry",
  "Messgeometrie",
  "Measurement geometry",
  "catalogue_thickness",
  "Dicke",
  "Thickness",
  "catalogue_type",
  "Transmissionsart",
  "Transmittance type",
  "catalogue_source_points",
  "Messpunkte in der Quelldatei",
  "Source measurement points",
  "catalogue_transformation",
  "Verarbeitung für Spectran",
  "Processing for Spectran",
  "aria_catalogue_information",
  "Quellen- und Messinformationen zum ausgewählten Katalogfilter",
  "Source and measurement information for the selected catalogue filter",
  "aria_parsed_table",
  "Scrollbare Tabelle der eingelesenen Transmissionswerte",
  "Scrollable parsed transmission rows table",
  "aria_status_table",
  "Scrollbare Statustabelle des vervollständigten Rasters",
  "Scrollable completed-grid status table",
  "plot_wavelength",
  "Wellenlänge (nm)",
  "Wavelength (nm)",
  "plot_transmittance",
  "Transmission (Anteil)",
  "Transmittance (fraction)",
  "plot_construction_legend",
  "Erzeugung der Kurve",
  "How the curve was constructed",
  "plot_invalid_one",
  "1 Wert liegt außerhalb von 0–1 und wird nicht dargestellt",
  "1 value is outside 0–1 and is not drawn",
  "plot_invalid_many",
  "%d Werte liegen außerhalb von 0–1 und werden nicht dargestellt",
  "%d values are outside 0–1 and are not drawn",
  "alt_construction_plot",
  "Konstruktionsdiagramm der gelieferten und vervollständigten Transmissionskurve von 380 bis 780 Nanometer. Farben und Formen unterscheiden gelieferte, interpolierte, angenommene und außerhalb des Bereichs liegende Werte.",
  "Construction plot of the supplied and completed transmission curve from 380 to 780 nanometres. Colours and shapes identify supplied, interpolated, assumed, and outside-range samples.",
  "undefined",
  "Nicht definiert",
  "Undefined",
  "plot_incident",
  "Einfallend",
  "Incident",
  "plot_transmitted",
  "Transmittiert",
  "Transmitted",
  "plot_spectral_irradiance",
  "Spektrale Bestrahlungsstärke (mW/m²/nm)",
  "Spectral irradiance (mW/m²/nm)",
  "plot_spectrum",
  "Spektrum",
  "Spectrum",
  "active_source",
  "Aktive Quelle",
  "Active source",
  "source_summary",
  "%s mW/m² Gesamtbestrahlungsstärke; %s lx photopische Beleuchtungsstärke.",
  "%s mW/m² total irradiance; %s lx photopic illuminance.",
  "transmission_filter",
  "Transmissionsfilter",
  "Transmission filter",
  "aria_applied_stale",
  "Veraltete Ergebnisse der angewendeten Transmission",
  "Out-of-date applied transmission results",
  "aria_applied_current",
  "Aktuelle Ergebnisse der angewendeten Transmission",
  "Current applied transmission results",
  "aria_applied_archived",
  "Archiviertes übernommenes Transmissionsergebnis",
  "Archived promoted transmission result",
  "aria_d65_table",
  "Tabelle der D65-bezogenen Filtereigenschaften",
  "D65-referenced filter properties table",
  "aria_absolute_table",
  "Tabelle der einfallenden und transmittierten Lichtkennwerte",
  "Incident and transmitted light metrics table",
  "aria_balance_table",
  "Tabelle der Änderungen von Wirkfaktoren und DER",
  "Action factor and DER changes table",
  "alt_spectral_comparison",
  "Liniendiagramm zum Vergleich der einfallenden und transmittierten spektralen Bestrahlungsstärke von 380 bis 780 Nanometer. Farbe und Linientyp unterscheiden die beiden Spektren.",
  "Line plot comparing the incident and transmitted spectral irradiance from 380 to 780 nanometres. Colour and line type distinguish the two spectra.",
  "alt_filter_panel",
  "Teilbild B mit dem Transmissionsspektrum des angewendeten Filters von 380 bis 780 Nanometer.",
  "Panel B showing the applied filter's transmittance spectrum from 380 to 780 nanometres.",
  "aria_history_table",
  "Tabelle des Transmissionsverlaufs dieser Sitzung",
  "Session transmission history table",
  "aria_archived_results",
  "Archivierte Ergebnisse übernommener Transmissionen",
  "Archived promoted transmission results",
  "aria_archived_d65_table",
  "Archivierte Tabelle der D65-bezogenen Filtereigenschaften",
  "Archived D65-referenced filter properties table",
  "aria_archived_absolute_table",
  "Archivierte Tabelle der einfallenden und transmittierten Kennwerte",
  "Archived incident and transmitted metrics table",
  "aria_archived_balance_table",
  "Archivierte Tabelle der Änderungen von Wirkfaktoren und DER",
  "Archived action factor and DER changes table",
  "alt_archived_spectral_comparison",
  "Liniendiagramm zum Vergleich der einfallenden und transmittierten spektralen Bestrahlungsstärke für das ausgewählte archivierte Ergebnis von 380 bis 780 Nanometer.",
  "Line plot comparing the incident and transmitted spectral irradiance for the selected archived promotion from 380 to 780 nanometres.",
  "alt_archived_filter_panel",
  "Teilbild B mit dem Transmissionsspektrum des Filters für das ausgewählte archivierte Ergebnis von 380 bis 780 Nanometer.",
  "Panel B showing the filter transmittance spectrum for the selected archived promotion from 380 to 780 nanometres.",
  "source_missing",
  "Es ist kein aktives Quellspektrum verfügbar.",
  "No active source spectrum is available.",
  "source_invalid",
  "Das aktive Quellspektrum hat keine gültige Struktur für diese Berechnung.",
  "The active source spectrum does not have a valid structure for this calculation.",
  "apply_not_ready",
  "Der Filter kann erst angewendet werden, wenn Quelle und Entwurf bereit sind.",
  "The filter cannot be applied until the source and draft are ready.",
  "apply_failed",
  "Der Filter konnte nicht angewendet werden. Prüfen Sie Quelle und Entwurf und versuchen Sie es erneut.",
  "The filter could not be applied. Check the source and draft, then try again.",
  "warning_detail_retained",
  "%s ist nicht definiert, weil der Nenner der einfallend gewichteten Wirkung null oder auf Maschinengenauigkeit nahe null ist.",
  "%s is undefined because its incident weighted-response denominator is zero or within machine precision of zero.",
  "warning_detail_retained_pair",
  "%s und %s sind nicht definiert, weil ihr gemeinsamer Nenner der einfallend gewichteten Wirkung null oder auf Maschinengenauigkeit nahe null ist.",
  "%s and %s are undefined because their shared incident weighted-response denominator is zero or within machine precision of zero.",
  "warning_detail_action",
  "%s ist nicht definiert, weil der Nenner der photopischen Wirkung null oder auf Maschinengenauigkeit nahe null ist.",
  "%s is undefined because its photopic response denominator is zero or within machine precision of zero.",
  "warning_detail_der",
  "%s ist nicht definiert, weil der Nenner der photopischen Beleuchtungsstärke null oder auf Maschinengenauigkeit nahe null ist.",
  "%s is undefined because its photopic illuminance denominator is zero or within machine precision of zero.",
  "warning_detail_generic",
  "%s ist nicht definiert, weil ein erforderlicher Nenner null oder auf Maschinengenauigkeit nahe null ist.",
  "%s is undefined because a required denominator is zero or within machine precision of zero.",
  "uploaded_filter",
  "Hochgeladener Filter",
  "Uploaded filter",
  "diagnostic_two_samples",
  "Geben Sie mindestens zwei Spektralwerte an.",
  "Supply at least two spectral samples.",
  "diagnostic_problem_values",
  "Problemwerte: %s.",
  "Problem values: %s.",
  "diagnostic_column_text",
  "Die Spalte wurde als Text eingelesen.",
  "The column was read as text.",
  "diagnostic_wavelength_not_numeric",
  "Die ausgewählte Wellenlängenspalte ist nicht numerisch. %s Prüfen Sie Dezimalzeichen, Kopfzeile, übersprungene Zeilen und Spaltenauswahl.",
  "The selected wavelength column is not numeric. %s Check the decimal mark, header setting, rows to skip, and column selections.",
  "diagnostic_transmission_not_numeric",
  "Die ausgewählte Transmissionsspalte ist nicht numerisch. %s Prüfen Sie Dezimalzeichen, Kopfzeile, übersprungene Zeilen und Spaltenauswahl.",
  "The selected transmission column is not numeric. %s Check the decimal mark, header setting, rows to skip, and column selections.",
  "diagnostic_choose_scale",
  "Wählen Sie Anteil oder Prozent als Transmissionsskala.",
  "Choose whether transmission is a fraction or percent.",
  "diagnostic_wavelength_missing",
  "Wellenlängen enthalten fehlende oder nicht endliche Werte bei %s. Prüfen Sie Dezimalzeichen, Kopfzeile, übersprungene Zeilen und Wellenlängenspalte.",
  "Wavelengths contain missing or non-finite values at %s. Check the decimal mark, header setting, rows to skip, and wavelength column.",
  "diagnostic_transmission_missing",
  "Transmissionen enthalten fehlende oder nicht endliche Werte bei %s. Prüfen Sie Dezimalzeichen, Kopfzeile, übersprungene Zeilen und Transmissionsspalte.",
  "Transmission contains missing or non-finite values at %s. Check the decimal mark, header setting, rows to skip, and transmission column.",
  "diagnostic_duplicates",
  "Doppelte Wellenlängen sind nicht zulässig: %s.",
  "Duplicate wavelengths are not allowed: %s.",
  "diagnostic_transmission_range",
  "Die Transmission muss nach der Skalierung zwischen 0 und 1 liegen. Betroffen: %s. Prüfen Sie, ob Anteil oder Prozent richtig ausgewählt ist.",
  "Transmission must be between 0 and 1 after scaling. Affected %s. Check whether Fraction or Percent is selected correctly.",
  "diagnostic_no_overlap",
  "Das gelieferte Spektrum überlappt oder umschließt den Bereich von 380–780 nm nicht.",
  "The supplied spectrum does not overlap or bracket 380–780 nm.",
  "diagnostic_parsed_columns",
  "Die Datei wurde in %d Spalte(n) eingelesen, ausgewählt waren jedoch Wellenlängenspalte %d und Transmissionsspalte %d. Prüfen Sie Trennzeichen, Dezimalzeichen, Kopfzeile und übersprungene Zeilen oder wählen Sie vorhandene Spalten.",
  "The file was parsed into %d column(s), but wavelength column %d and transmission column %d were selected. Check the separator, decimal mark, header setting, and rows to skip, or select available columns.",
  "diagnostic_csv_parse",
  "Die Spektral-CSV konnte mit den ausgewählten Einstellungen nicht eingelesen werden. Prüfen Sie Trennzeichen, Dezimalzeichen, Kopfzeile und übersprungene Zeilen.",
  "The spectral CSV could not be parsed with the selected settings. Check the separator, decimal mark, header setting, and rows to skip.",
  "file_receiving",
  "Datei wird empfangen",
  "Receiving file",
  "file_received",
  "Datei empfangen",
  "File received"
)

transmission_language_rows$Name <- paste0(
  "transmission.",
  transmission_language_rows$key
)
transmission_language_rows$Ort <- "Transmission"

language_path <- file.path("data-raw", "languages.xlsx")
if (file.exists(language_path)) {
  existing_ui <- openxlsx::read.xlsx(language_path, sheet = "ui")
  existing_ui <- existing_ui[
    !existing_ui$Name %in% transmission_language_rows$Name,
    ,
    drop = FALSE
  ]
  new_rows <- data.frame(
    Ort = transmission_language_rows$Ort,
    Zelle_nach.Import = seq.int(
      nrow(existing_ui) + 1L,
      nrow(existing_ui) + nrow(transmission_language_rows)
    ),
    Name = transmission_language_rows$Name,
    Deutsch = transmission_language_rows$Deutsch,
    English = transmission_language_rows$English,
    check.names = FALSE
  )
  updated_ui <- rbind(existing_ui, new_rows)
  updated_ui$Deutsch[updated_ui$Name == "lang$ui(62)"] <-
    "Spektrum importieren und zur Auswertung wechseln"
  updated_ui$English[updated_ui$Name == "lang$ui(62)"] <-
    "Import spectrum and open Analysis"
  updated_ui$Deutsch[updated_ui$Name == "lang$ui(91)"] <-
    "Spektrum übernehmen und zur Auswertung wechseln"
  updated_ui$English[updated_ui$Name == "lang$ui(91)"] <-
    "Use spectrum and open Analysis"
  workbook <- openxlsx::loadWorkbook(language_path)
  openxlsx::removeWorksheet(workbook, "ui")
  openxlsx::addWorksheet(workbook, "ui", gridLines = TRUE)
  openxlsx::writeData(workbook, "ui", updated_ui)
  openxlsx::setColWidths(workbook, "ui", cols = 1:5, widths = "auto")
  openxlsx::saveWorkbook(workbook, language_path, overwrite = TRUE)
}

rm(transmission_language_rows, language_path)
