name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: rocker/shiny:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: R -e 'install.packages("rsconnect", repos="http://cran.rstudio.com/")'
    - name: Deploy English App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        CONFIG_ENV: default
      run: R -e 'Sys.setenv(CONFIG_ENV = Sys.getenv("CONFIG_ENV")); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_en")'
    - name: Deploy German App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        CONFIG_ENV: deutsch
      run: R -e 'Sys.setenv(CONFIG_ENV = Sys.getenv("CONFIG_ENV")); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_de")'
