name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  deploy:
    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/litgde/spectran:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v2
    - name: check files and dirs
      run: R -e 'list.files("renv"); list.files("/__w"); list.dirs(path = "/")'
    - name: Install packages
      run: R -e 'install.packages("R.utils"); R.utils::copyDirectory(from = "../renv", to = "renv"); renv::restore()'
    - name: Deploy English App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: R -e 'writeLines("language = English", ".Renviron"); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_en", forceUpdate = TRUE)'
    - name: Deploy German App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: R -e 'writeLines("language = Deutsch", ".Renviron"); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_de", forceUpdate = TRUE)'
