name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  deploy:
    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    container: rocker/shiny:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev libxml2-dev
    - name: Install dependencies
      run: R -e 'renv::restore()'
    - name: Deploy English App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        CONFIG_ENV: default
      run: R -e 'Sys.setenv(CONFIG_ENV = Sys.getenv("CONFIG_ENV")); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_en")'
    - name: Deploy German App
      env:
        SHINYAPPS_ACCOUNT: litg
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        CONFIG_ENV: deutsch
      run: R -e 'Sys.setenv(CONFIG_ENV = Sys.getenv("CONFIG_ENV")); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp(appName="Spectran_de")'
